"""
Django settings for employee_management project.

Generated by 'django-admin startproject' using Django 4.2.20.
"""

import os
from pathlib import Path

# --------------------------------------------------------
# Base Directory
# --------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------------------
# Security
# --------------------------------------------------------
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-o5^8l=)fh)la8p#azru&7!r@@#&o=lr)c@&e1_16aly2*22(s4')
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'
ALLOWED_HOSTS = ['*']  # Render or any domain will work

# --------------------------------------------------------
# Installed Apps
# --------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'employee',
]

# --------------------------------------------------------
# Middleware
# --------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ✅ Serve static files in production
    'corsheaders.middleware.CorsMiddleware',       # ✅ CORS support
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------------------------------------------
# URL & WSGI
# --------------------------------------------------------
ROOT_URLCONF = 'employee_management.urls'
WSGI_APPLICATION = 'employee_management.wsgi.application'

# --------------------------------------------------------
# Templates
# --------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# --------------------------------------------------------
# Database (MySQL on Railway or Render)
# --------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'railway'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'hSKtIozJkKIOwMSSzTtGcSWiokJnVkdQ'),
        'HOST': os.getenv('DB_HOST', 'shortline.proxy.rlwy.net'),
        'PORT': os.getenv('DB_PORT', '16985'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        },
    }
}

# --------------------------------------------------------
# Password Validation
# --------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --------------------------------------------------------
# Internationalization
# --------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --------------------------------------------------------
# Static Files
# --------------------------------------------------------
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --------------------------------------------------------
# Default Auto Field
# --------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------------------------------------
# CORS Configuration
# --------------------------------------------------------
CORS_ALLOW_ALL_ORIGINS = True  # ✅ Allow all React/frontend origins (any URL)
CORS_ALLOW_CREDENTIALS = True  # ✅ Allow cookies/JWT
